image: node:8

stages:
  - install
  - lint
  - test
  - build
  - clean_up

install:
  stage: install
  script:
    - apt-get -qq update
    - apt-get -qq install -y python2.7 python2.7-dev build-essential make gcc g++ libicu-dev

    - npm install
  cache:
    key: ${CI_BUILD_ID}
    paths:
      - node_modules
  artifacts:
    paths:
     - node_modules/

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
    - npm run docs
  artifacts:
    paths:
     - dist/
     - docs/

clean_up_job:
  stage: clean_up
  script:
    - rm -rf node_modules
    - rm -rf ~/.node-gyp
  when: on_failure
